# Generated by Django 4.0.3 on 2022-04-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('select', 'Select'), ("product doesn't exsist", "Product doesn't exsist"), ('in Stock', 'In Stock')], default='select', max_length=50),
        ),
    ]
