# Generated by Django 4.0.3 on 2022-04-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_brand_category_product_category_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(),
        ),
    ]
