# Generated by Django 4.0.3 on 2022-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_product_packeting_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('no information', 'No information'), ("product doesn't exsist", "Product doesn't exsist"), ('in Stock', 'In Stock')], default='no information', max_length=50),
        ),
    ]
