# Generated by Django 4.0.3 on 2022-05-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
