# Generated by Django 4.0.3 on 2022-05-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
