# Generated by Django 4.0.3 on 2022-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
