# Generated by Django 4.0.3 on 2022-05-13 14:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_products_product_name_az_products_product_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='description_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
