# Generated by Django 4.0.3 on 2022-05-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_colours_products_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('10 to 30', '10 to 30'), ('30 to 50', '30 to 50'), ('50 to 100', '50 to 100')], max_length=100)),
            ],
        ),
    ]
