# Generated by Django 4.0.3 on 2022-04-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_image/')),
                ('created_add', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('short_description_1', models.CharField(max_length=200)),
                ('short_description_2', models.CharField(max_length=200)),
                ('short_description_3', models.CharField(max_length=200)),
                ('short_description_4', models.CharField(max_length=200)),
                ('short_description_5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('created_add', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
