# Generated by Django 4.0.3 on 2022-04-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reject', 'Reject'), ('approve', 'Approve')], default='reject', max_length=50)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_all_comments', to='Blog.blog')),
            ],
            options={
                'ordering': ['-date_add'],
            },
        ),
    ]
