# Generated by Django 4.0.3 on 2022-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127)),
                ('subject', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=127)),
                ('days_open', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127)),
                ('short_text', models.CharField(max_length=100)),
            ],
        ),
    ]
